
modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="feur_shadow_elytra"
version="1.1.0"
displayName="Feur Shadow Elytra (Repainted)"
authors="you"
description='''Adds a shadow Elytra item and embedded repainted textures mapped to [Wing001]..'''

[[dependencies.feur_shadow_elytra]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.feur_shadow_elytra]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
