name: build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build
        shell: pwsh
        run: |
          if (Test-Path .\gradlew.bat) {
            echo "Using Gradle Wrapper"
            .\gradlew.bat build
          } else {
            echo "Gradle wrapper not found. Downloading Gradle 8.7..."
            Invoke-WebRequest -Uri https://services.gradle.org/distributions/gradle-8.7-bin.zip -OutFile gradle.zip
            Expand-Archive gradle.zip -DestinationPath .
            .\gradle-8.7\bin\gradle.bat build
          }

      - name: Upload Jar
        uses: actions/upload-artifact@v4
        with:
          name: feur_shadow_elytra
          path: build\libs\*.jar
